# Generated by Django 3.2.12 on 2023-09-27 14:05

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_time']},
        ),
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
